name = input('이름을 입력하세요: ')
id = input('학번을 입력하세요: ')
de = input('학과를 입력하세요: ')
sc = input('학과를 입력하세요: ')
gr = input('학년를 입력하세요: ')

print()
print("<출력>")
print("이름: ",name)
print("학번: ",id)
print("학과: ",de)
print("학교: ",sc)
print("학년: ",gr)